### ISSUE TITLE
System.IO.DirectoryNotFoundException: Could not find a part of the path

### ISSUE THREAD

**Issue by Probe1** [Robspie/logfileanalyzer#1]
1.  Download a server log http://game.ss13.moe/logs/2016/06-June/
2.  Run exe
3.  Search 'hello'
4.  Receive listed error and request to post it here.

```

System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Eric\Downloads\logFileAnalyzer\6-27\+hello ; -;2369834.tmp'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path)
   at Log_File_Analyzer_V2.searchResultForm.searchResultForm_Load(Object sender, EventArgs e)

```

**Comment by Probe1** [comment]
Could not reproduce a second time.  Seems to work fine now by repeating the same steps.
